services:
  grafana:
    build: ./grafana
    ports:
      - '80:3000'
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
    container_name: grafana
    depends_on:
      - prometheus

  prometheus:
    build: ./prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=2d'
    restart: unless-stopped
    container_name: prometheus
    depends_on:
      - network-exporter

  network-exporter:
    build: ./network-exporter
    environment:
      API_KEY: ${API_KEY}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    privileged: true
    container_name: network-exporter
