services:
  grafana-glueops-gluekube-monitor:
    build: ./grafana
    ports:
      - '60080:3000'
    restart: unless-stopped
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: grafana
    container_name: grafana-glueops-gluekube-monitor
    depends_on:
      - prometheus-glueops-gluekube-monitor

  prometheus-glueops-gluekube-monitor:
    build: ./prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.retention.time=14d'
    restart: unless-stopped
    container_name: prometheus-glueops-gluekube-monitor
    depends_on:
      - network-exporter-glueops-gluekube-monitor

  network-exporter-glueops-gluekube-monitor:
    build: ./network-exporter
    environment:
      API_KEY: ${API_KEY}
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: unless-stopped
    privileged: true
    container_name: network-exporter-glueops-gluekube-monitor
